language: elixir

services:
  - postgresql

elixir:
  - 1.8.2
otp_release:
  - 22.0.3

before_script:
  - psql -c 'create database core_test;' -U postgres

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
  - mix dialyzer --halt-exit-status

cache:
  directories:
    - _build
    - deps

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
