---
all:
  hosts:
    auth:
      ansible_host: 192.168.33.10
      ansible_user: vagrant
  vars:
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"

applications:
  hosts:
    auth:
