---
all:
  hosts:
    apiumbrella-build:
      ansible_host: 192.168.33.9
    apiumbrella-auth:
      ansible_host: 192.168.33.10
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: vagrant
    ansible_ssh_private_key_file: ".vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key"

applications:
  hosts:
    apiumbrella-build:
#    apiumbrella-auth:
