---
- name: Setup Vagrant
  hosts: applications

  become: true
  become_user: root
  become_method: sudo

  vars:
    elixir_version: "1.9.1"
    erlang_version: "22"
    nodejs_version: "11"
    postgresql_version: "11"
    nginx_hosts:
      - auth.server.dev
  pre_tasks:
    - name: install packages
      apt:
        name:
          - git
          - mc
          - mlocate
          - curl
          - vim
  roles:
    - weareinteractive.environment
    - erlang
    - elixir
    - nodejs
    - postgresql
    - mkcert
    - nginx
