---
- name: Setup Vagrant
  hosts: applications

  become: true
  become_user: root
  become_method: sudo

  vars:
    elixir_package: "elixir=1.9.1-1"
    erlang_package: "esl-erlang=1:22.1-1"
    nodejs_version: "11.x"
    nodejs_package: "nodejs=11.15.0-1nodesource1"

  roles:
    - erlang
    - elixir
    - nodejs
