---
- name: Setup Vagrant
  hosts: applications

  become: true
  become_user: root
  become_method: sudo

  vars:
    elixir_package: "elixir=1.9.1-1"
    erlang_package: "esl-erlang=1:22.1-1"

  pre_tasks:
    - name: Wait for ssh to be up
      become: false
      wait_for:
        port: 22
        delay: 5
        connect_timeout: 5
        timeout: 360
        host: "{{ ansible_host }}"
      delegate_to: localhost
  roles:
    - erlang
    - elixir
