name: Node CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '10', '8' ]
    container:
      image: elixir:1.9.1-slim
    steps:
      - uses: actions/checkout@v1

      - name: Install Phoenix Dependencies
        run: |
          mix deps.get

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: |
          npm install -g yarn
          cd ./apps/core_web/assets/
          yarn install

      - name: Run test
        run: |
          yarn run test


